### ISSUE TITLE
Iconv-lite warning

### ISSUE THREAD

**Issue by shahidmau** [craftzdog/extract-main-text-node#1]
Thanks for awesome library. I am getting below error. Kindly help.

Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding

**Comment by craftzdog** [comment]
Fixed in v1.0.2
Thanks for the report!

**Comment by shahidmau** [comment]
Thanks for reply. Its still not working for me. I am getting this kind of response

Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding
5243 '*' 1 '=' 5243 5233
70.81 '*' 1 '=' 70.81 97
67.1454 '*' 0.23520955289486503 '=' 15.793239512946869 126
50.183192999999996 '*' 0.1451910820338673 '=' 7.286152091584395 129
28.114258589999995 '*' 0.055323533773002316 '=' 1.5553801346067853 99
19.694180133499998 '*' 0.0341503294895076 '=' 0.6725627405847397 95
32.688192878424 '*' 0.013012623643311842 '=' 0.4253591515069179 216
22.757640949339816 '*' 0.004958323290394697 '=' 0.11283974115355169 206
16.85501592058629 '*' 0.001889316906871931 '=' 0.03184446654435924 209
12.421904795444528 '*' 0.0007199043236061313 '=' 0.008942582969664251 211
8.767156692595258 '*' 0.00027431196601361503 '=' 0.0024049359886952277 204
3.1058941871267605 '*' 0.0000645207948797738 '=' 0.00020039476176588752 99
6.137748876459388 '*' 0.00002458496985207049 '=' 0.00015089637108733358 268
2.156685864537987 '*' 0.000009367844022279564 '=' 0.000020203496784047015 129

**Comment by craftzdog** [comment]
weird. It's working correctly on CircleCI:
https://circleci.com/gh/craftzdog/extract-main-text-node/3

Can you run `npm test` and check if it's passed?

**Comment by shahidmau** [comment]
172-1-0-69:extract-main-text apple$ npm test

> extract-main-text@1.0.2 test /Volumes/disk2/programs/nodejs/scrap/node_modules/extract-main-text
> mocha --harmony

sh: mocha: command not found
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by shahidmau** [comment]
hello sorry, I installed mocha and executed test and everything looks passed. But script is still giving error. I am trying below code.


var BodyExtractor = require('extract-main-text');
var extractor = new BodyExtractor({
    url: 'http://www.channelnewsasia.com/news/singapore/s-100-million-raised-for-ntuc-s-education-and-training-fund-8808448'
  });
extractor.analyze()
  .then(function(text) {
    console.log(extractor.title);
    console.log(extractor.bodmainText);
  });

**Comment by craftzdog** [comment]
I ran your code but no warning produced.
What's your node version?

**Comment by shahidmau** [comment]
172-1-0-69:scrap apple$ node -v
v7.7.2

**Comment by craftzdog** [comment]
I got no warning with node 7.7.2. Please install node modules again.

BTW, you can suppress debug output like so:

```js
var extractor = new BodyExtractor({
  url: 'http://www.channelnewsasia.com/news/singapore/s-100-million-raised-for-ntuc-s-education-and-training-fund-8808448'
}, { debug: false });
```

**Comment by shahidmau** [comment]
After debug: false, body is coming "undefined"

**Comment by craftzdog** [comment]
fix from `extractor.bodmainText ` to `extractor.mainText`

**Comment by craftzdog** [comment]
oh that's my fault, sorry. I fixed readme.

**Comment by shahidmau** [comment]
thanks, its working for me. But I am getting html tags in the content. 

`<meta property="og:description" content="SINGAPORE: Four foreign women were arrested on Thursday (May 4) for their suspected involvement in vice-related activities, the police said on Friday...
`

**Comment by craftzdog** [comment]
It seems that the eliminating tags is unstable.
Please remove them by using other library.

**Comment by shahidmau** [comment]
ok thanks 👍
